### ISSUE TITLE
Build errors from ptp.cpp on 1.0 version

### ISSUE THREAD

**Issue by Fanta-astic** [erezgeva/libptpmgmt#1]
Hello, I'm interested in trying your project out but I am hitting a build issue with errors coming from ptp.cpp.

I am seeing the same output from the 1.0 tag and the master branch.
I am not very familiar with cpp, so this could very well be an environment issue. Any suggestions you have are appreciated.

Let me know if you need any more information.

Here is the output from make all:

/githolder/libptpmgmt-code$ make clean
Cleaning

/githolder/libptpmgmt-code$ make all
running CONFIG_SHELL=/bin/bash /bin/bash ./configure --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --libexecdir=${prefix}/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking build_alias=x86_64-linux-gnu CXXFLAGS=-g -O2 -fdebug-prefix-map=/home/user/githolder/libptpmgmt-code=. -fstack-protector-strong -Wformat -Werror=format-security LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2 --no-create --no-recursion
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ranlib... ranlib
checking for a sed that does not truncate output... /usr/bin/sed
checking for a BSD-compatible install... /usr/bin/install -c
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking whether ln -s works... yes
checking for m4... m4
checking for ctags... ctags
checking for pkg-config... pkg-config
checking for astyle... no
checking for astyle version... not found
checking for astyle minimum version... not found
checking for cppcheck... no
checking for doxygen... doxygen
checking for doxygen version... 1.8.17
checking for doxygen minimum version... 1.8.17
checking for dot... dot
checking for cross compilation... not found
checking for project root folder... /home/user/githolder/libptpmgmt-code
checking how to run the C++ preprocessor... g++ -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gtest/gtest.h usability... no
checking gtest/gtest.h presence... no
checking for gtest/gtest.h... no
checking json-c/json.h usability... no
checking json-c/json.h presence... no
checking for json-c/json.h... no
checking libfastjson/json.h usability... yes
checking libfastjson/json.h presence... yes
checking for libfastjson/json.h... yes
checking for package version string... 1.0
checking for package version major... 1
checking for package version minor... 0
checking for package version value... 0x0100
checking for swig... swig
checking for swig version... 4.0.1
checking for swig minimum version... 4.0.1
checking for swig library... /usr/share/swig4.0
checking for swig argcargv... true
checking for build wrapper... yes
checking for Tcl configuration... found /usr/lib/tcl8.6/tclConfig.sh
checking for Tcl version... 8.6
checking for Tcl package path... /usr/lib/tcltk/x86_64-linux-gnu
checking for Tcl header files... -I/usr/include/tcl8.6
checking for Tcl library... -L/usr/lib/x86_64-linux-gnu -ltcl8.6
checking for python3... python3
checking for python3-config... python3-config
checking for python3 major version number... 3
checking for Python 3.x version... python3.8
checking for Python 3.x header files... -I/usr/include/python3.8 -I/usr/include/python3.8
checking for Python 3.x site folder... /usr/lib/python3.8/dist-packages
checking for Python 3.x library... -lpython3.8
checking for Python 3.x extension suffix... .cpython-38-x86_64-linux-gnu.so
checking for Python 3.x linking...  -lcrypt -lpthread -ldl  -lutil -lm -lm
checking for perl... perl
checking for Perl5 confiuration... /usr/lib/x86_64-linux-gnu/perl/5.30
checking for Perl5 header files... /usr/lib/x86_64-linux-gnu/perl/5.30/CORE
checking for ruby... ruby
checking for Ruby header files... -I/usr/include/ruby-2.7.0 -I/usr/include/x86_64-linux-gnu/ruby-2.7.0
checking for Ruby header folder... /usr/include/ruby-2.7.0
checking for Ruby header architecture folder... /usr/include/x86_64-linux-gnu/ruby-2.7.0
checking for Ruby version... ruby-2.7
checking for Ruby library... /usr/lib/x86_64-linux-gnu
checking for Ruby link flags... -lruby-2.7 -lm
checking for Ruby site... /usr/lib/x86_64-linux-gnu/ruby/vendor_ruby/2.7.0
checking for php8.1... no
checking for php8.0... no
checking for php7.4... php7.4
checking for php-config7.4... php-config7.4
checking for PHP include folder... /usr/share/php
checking for PHP version... 7.4.3-4ubuntu2.18
checking for PHP extensions... /usr/lib/php/20190902
checking for PHP headers base folder... /usr/include/php/20190902
checking for PHP header files... -I${PHPINC} -I${PHPINC}/main -I${PHPINC}/TSRM -I${PHPINC}/Zend -I${PHPINC}/ext -I${PHPINC}/ext/date/lib
checking for lua5.7... no
checking for lua5.6... no
checking for lua5.5... no
checking for lua5.4... no
checking for lua5.3... /usr/bin/lua5.3
configure: creating ./config.status
config.status: creating defs.mk
[GEN] src/ids.h
[GEN] src/mngIds.h
[GEN] src/callDef.h
[GEN] src/ver.h
[CC] tools/pmc_dump.cpp
[CC] tools/pmc.cpp
[LCC] src/cfg.cpp
[LCC] src/proc.cpp
[LCC] src/bin.cpp
[LCC] src/msgCall.cpp
[LCC] src/init.cpp
[LCC] src/buf.cpp
[LCC] src/sock.cpp
[LCC] src/ptp.cpp
src/ptp.cpp: In member function ‘bool ptpmgmt::PtpClock::fetchCaps(ptpmgmt::PtpCaps_t&) const’:
src/ptp.cpp:380:29: error: ‘struct ptp_clock_caps’ has no member named ‘adjust_phase’
  380 |     caps.adjust_phase = cps.adjust_phase > 0;
      |                             ^~~~~~~~~~~~
src/ptp.cpp: In member function ‘bool ptpmgmt::PtpClock::setPinPeriod(unsigned int, ptpmgmt::PtpPinPeriodDef_t, uint8_t) const’:
src/ptp.cpp:565:20: error: ‘struct ptp_perout_request’ has no member named ‘on’
  565 |         fromTs(req.on, times.width);
      |                    ^~
src/ptp.cpp:567:20: error: ‘struct ptp_perout_request’ has no member named ‘phase’
  567 |         fromTs(req.phase, times.phase);
      |                    ^~~~~
make: *** [Makefile:336: objs/ptp.o] Error 1

**Comment by Fanta-astic** [comment]
Looking further, this may be an issue with the header file installed on my system.

I can see that struct for ptp_perout_request in my /usr/include/linux/ptp_clock.h doesn't have some of fields. Going to check if I can update that header file.

**Comment by Fanta-astic** [comment]
Ok, I think I have resolved this.
I am building on Ubuntu lts 2020, which has an outdated linux-libc-dev package: [https://packages.ubuntu.com/focal/linux-libc-dev](https://packages.ubuntu.com/focal/linux-libc-dev)
The ptp_clock.h file is 3 years old and missing stuff that libptpmgmt uses.

To resolve, I downloaded a newer version from [https://launchpad.net/ubuntu/jammy/amd64/linux-libc-dev/5.15.0-25.25](https://launchpad.net/ubuntu/jammy/amd64/linux-libc-dev/5.15.0-25.25)

and then installed it with
sudo dpkg -i linux-libc-dev_5.15.0-25.25_amd64.deb

Build worked fine after that! 💯

**Comment by erezgeva** [comment]
#ifdef PTP_CLOCK_GETCAPS2
    caps.adjust_phase = cps.adjust_phase > 0;
    #else
    caps.adjust_phase = false;
    #endif



With old [linux-libc-dev](https://packages.ubuntu.com/focal/linux-libc-dev), the `PTP_CLOCK_GETCAPS2` and `PTP_PEROUT_REQUEST2` should not be defined.

What version of linux-libc-dev did you use?
I want to add a note in the FAQ on it.

The second error

    #ifndef PTP_PEROUT_REQUEST2
    ...
    #else
    .... 
    req.on

**Comment by erezgeva** [comment]
I might need to pass the probe of `caps.adjust_phase` and `req.on` to the configure, and not rely on the `PTP_CLOCK_GETCAPS2` and `PTP_PEROUT_REQUEST2` solely.

**Comment by Fanta-astic** [comment]
Thanks for responding!

It was the version available for Ubuntu LTS 20.04, which is linux-libc-dev (5.4.0-148.165)
It is available here [https://packages.ubuntu.com/focal/linux-libc-dev](https://packages.ubuntu.com/focal/linux-libc-dev)

I think it should correspond to this version of ptp_clock.h
[https://github.com/torvalds/linux/blob/6138e687c7b679da08c0feb55a88f448f7890c07/include/uapi/linux/ptp_clock.h](https://github.com/torvalds/linux/blob/6138e687c7b679da08c0feb55a88f448f7890c07/include/uapi/linux/ptp_clock.h)

Let me know if you would like me to test anything out in my environment.

**Comment by erezgeva** [comment]
Yes, good catch.
The ioctl macros were added in 2019-09-11,  kernel 5.3

And the new fields were added in 2020-05-01 and 2020-07-17, kernel 5.8

So any linux-libc-dev in this rage will breaks.

I will add  probe of `caps.adjust_phase` and `req.on` to the configure stage, in addition of using `PTP_CLOCK_GETCAPS2` and `PTP_PEROUT_REQUEST2`.

Thanks for reporting the error.

I will close the issue after I commit the fix.

**Comment by erezgeva** [comment]
Upgrading the linux-libc-dev is a good idea regardless of the bug.
If you want to use these new features of the kernel PTP, provided by the `PtpClock` class.

**Comment by erezgeva** [comment]
I add probe in the configuration.
Version Kernel/linux-libc-dev 5.3 to 5.8 should work.

Thanks @Fanta-astic for catching the bug.

P.S.
Debian packages build on Ubuntu should work.
